language: generic 

sudo: required
services: 
  - docker

before_install: 
  - docker build -t chrissamharris/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true chrissamharris/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "Docker-React"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-298625819089"
  bucket_path: "Docker-React"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key